# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/ruby:2.5.3-node-browsers
        environment: # environment variables for primary container
          BUNDLE_JOBS: 3
          BUNDLE_RETRY: 3
          BUNDLE_PATH: vendor/bundle
          PGHOST: 127.0.0.1
          PGUSER: circleci
          RAILS_ENV: test

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      - image: circleci/postgres:11.1-alpine-ram
        environment:
          POSTGRES_USER: circleci
          POSTGRES_DB: cvwo_tasktracker
          POSTGRES_PASSWORD: ''

    working_directory: ~/tasktracker

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          name: Restore bundle cache
          keys:
            - tasktracker-v1-bundle-{{ checksum "Gemfile.lock" }}
            # fallback to using the latest cache if no exact match is found
            - tasktracker-v1-bundle-

      - restore_cache:
          name: Restore yarn cache
          keys:
            - tasktracker-v1-yarn-{{ checksum "yarn.lock" }}
            # fallback to using the latest cache if no exact match is found
            - tasktracker-v1-yarn-

      - run:
          name: bundle install
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle

      - run:
          name: yarn install
          command: |
            yarn install

      - save_cache:
          name: Save bundle cache
          paths:
            - ./vendor/bundle
          key: tasktracker-v1-bundle-{{ checksum "Gemfile.lock" }}

      - save_cache:
          name: Save yarn cache
          paths:
            - ./node_modules
          key: tasktracker-v1-yarn-{{ checksum "yarn.lock" }}

      # Database setup
      - run: bundle exec rake db:create
      - run: bundle exec rake db:schema:load

      # webpacker
      - run: RAILS_ENV=test bundle exec rails webpacker:compile

      # run tests!
      - run:
          name: run tests
          command: |
            mkdir /tmp/test-results
            TEST_FILES="$(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)"

            bundle exec rspec

      # collect reports
      - store_artifacts:
          path: ~/tasktracker/coverage
          destination: coverage
          
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
